FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  build-essential \
  doxygen \
  git \
  python-dev \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*

# Install  Conan package manager and CMake
RUN pip3 install conan cmake
