#!/bin/bash
#
# This script performs the following operations:
#  - Fixes file permissions
#  - Ensures that all text files end with a newline
#  - Runs clang-format on all source files
#
set -o errexit -o nounset -o pipefail

# Regex to select files to run clang-format on
readonly clangFormattableFiles='.(h|c|hpp|cpp)$'

# Per-file corrections
for f in $(git ls-files); do
    # Ensure that only executable files have executable permissions
    if { file "$f" | grep -q " executable"; }; then
        chmod -c 0755 "$f"
    else
        chmod -c 0644 "$f"
    fi

    # Ensure that all text files end with a newline
    if { file "$f" | grep -q " text"; }; then
        { tail -c1 "$f" | read -r _; } || { echo >> "$f"; echo "appended newline to '$f'"; }
    fi
done

# Apply clang-format to all relevant source files
echo "running clang-format"
clang-format -i -style=file $(git ls-files | egrep "$clangFormattableFiles")
